defaults: &defaults
  adapter: postgres
  encoding: unicode
  pool: 5
  min_messages: warning
  host: localhost
  database: waldorfcamp

production:
  <<: *defaults
  username: deploy
  password: foobar

development:
  <<: *defaults

test:
  <<: *defaults
